NO-ISSUE: Temporary fix for UBI10 Go 1.26 issue
Currently the installation of the Go package fails with this error:

```
[1/2] STEP 1/9: FROM registry.access.redhat.com/ubi10/ubi:10.1-1773895909 AS builder

...
Error:
 Problem: package golang-bin-1.26.2-2.el10_2.x86_64 from ubi-10-for-x86_64-appstream-rpms requires gcc, but none of the providers can be installed
  - package golang-1.26.2-2.el10_2.x86_64 from ubi-10-for-x86_64-appstream-rpms requires golang-bin = 1.26.2-2.el10_2, but none of the providers can be installed
  - package gcc-14.3.1-4.4.el10.x86_64 from ubi-10-for-x86_64-appstream-rpms requires glibc-devel >= 2.2.90-12, but none of the providers can be installed
  - conflicting requests
  - nothing provides glibc = 2.39-124.el10_2 needed by glibc-devel-2.39-124.el10_2.x86_64 from ubi-10-for-x86_64-appstream-rpms
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: building at STEP "RUN set -e;   pkgs=(git golang);   dnf install -y "${pkgs[@]}";   dnf clean all -y": while running runtime: exit status 1
```

To address that this patch introduces a temporary fix: download the Go tarball
from the releases package and install it manually.

Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>